### ISSUE TITLE
When using the mod, the ability to craft completely disappears

### ISSUE THREAD

**Issue by unhack12** [nvb-uy/Item_Obliterator#9]
When using the mod, the ability to craft completely disappears, even if the config is empty
Item_Obliterator-FORGE-MC1.20.1-1.6.0.jar
_9th November updated:_ For the forge version, the problem was resolved with update 1.6.1! Thanks to the author for the prompt solution to the problem. I won't close the thread for this issue cause apparently this problem is still present in the fabric version

**Comment by MarcelLZ** [comment]
Yeah! Same issue here!

Error log:
`[13:43:23] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2840@36ea5223, suppressing error
java.lang.ClassCastException: class net.minecraft.class_8786 cannot be cast to class net.minecraft.class_1860 (net.minecraft.class_8786 and net.minecraft.class_1860 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1bce4f0a)
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.class_1863.handler$zoa000$item_obliterator$getRecipeForRecipeType(class_1863.java:1023) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_8132(class_1863.java:77) ~[server-intermediary.jar:?]
	at net.minecraft.class_1714.method_17399(class_1714.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_1714.method_17401(class_1714.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_3914.method_17394(class_3914.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_3914$2.method_17395(class_3914.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3914.method_17393(class_3914.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_1714.method_7609(class_1714.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_1715.method_5447(class_1715.java:68) ~[server-intermediary.jar:?]
	at net.minecraft.class_1735.method_7673(class_1735.java:75) ~[server-intermediary.jar:?]
	at net.minecraft.class_2955.method_12824(class_2955.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_2955.method_12815(class_2955.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.class_2952.method_12816(class_2952.java:51) ~[server-intermediary.jar:?]
	at net.minecraft.class_2955.method_12821(class_2955.java:105) ~[server-intermediary.jar:?]
	at net.minecraft.class_2955.method_12826(class_2955.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_1729.method_17697(class_1729.java:17) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_17820(class_3244.java:1670) ~[server-intermediary.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.class_3244.method_12061(class_3244.java:1670) ~[server-intermediary.jar:?]
	at net.minecraft.class_2840.method_12317(class_2840.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_2840.method_11054(class_2840.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:43:28] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2813@612e520f, suppressing error
net.minecraft.class_148: Container click
	at net.minecraft.class_1703.method_7593(class_1703.java:304) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12076(class_3244.java:1640) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_8786 cannot be cast to class net.minecraft.class_1860 (net.minecraft.class_8786 and net.minecraft.class_1860 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1bce4f0a)
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.class_1863.handler$zoa000$item_obliterator$getRecipeForRecipeType(class_1863.java:1023) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_8132(class_1863.java:77) ~[server-intermediary.jar:?]
	at net.minecraft.class_1714.method_17399(class_1714.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_1714.method_17401(class_1714.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_3914.method_17394(class_3914.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_3914$2.method_17395(class_3914.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3914.method_17393(class_3914.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_1714.method_7609(class_1714.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_1715.method_5447(class_1715.java:68) ~[server-intermediary.jar:?]
	at net.minecraft.class_1735.method_7673(class_1735.java:75) ~[server-intermediary.jar:?]
	at net.minecraft.class_1735.method_48931(class_1735.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_1735.method_53512(class_1735.java:63) ~[server-intermediary.jar:?]
	at net.minecraft.class_1735.method_32755(class_1735.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_30010(class_1703.java:412) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_7593(class_1703.java:294) ~[server-intermediary.jar:?]
	... 17 more`

**Comment by MarcelLZ** [comment]
Mod version: Item_Obliterator-Fabric_Quilt-MC1.20.1-1.6.1hf.jar
Downloaded from CurseForge

I'm running Minecraft 1.20.2

**Comment by nvb-uy** [comment]
Fixed last version
